"Adults" = "4332"
"- 50+" = "4333"
"Book Lovers" = "4334"
"Businesspeople" = "4335"
"Children" = "4336"
"- Infant (0-18 months)" = "4337"
"- Toddlers (18-36 months)" = "4338"
"- Pre-schoolers (3-5 years)" = "4339"
"- School Age (5-12 years)" = "4340"
"College &amp; Graduate Students" = "4341"
"English Language Learners" = "4342"
"Families" = "4343"
"Incarcerated Persons/Previously Incarcerated Persons (not for public website)" = "4345"
"Job Seekers" = "4346"
"Journalists (not for public website)" = "4347"
"NYPL Supporters" = "4348"
"Parents/Caregivers" = "4349"
"Persons with Disabilities" = "4350"
"Persons Without Homes" = "4351"
"Teachers" = "4352"
"- Early Childhood Educators" = "4353"
"- K-12 Educators" = "4354"
"- College/Graduate School Educators" = "4355"
"Teens/Young Adults (13-18 years)" = "4356"
"Young Adults/Pre GED (16-24 years)" = "5311"
