"None" = "_none"
"Anime &amp; Manga" = "4257"
"Art &amp; Photography" = "4255"
"Arts &amp; Crafts" = "4256"
"Board/Card Games" = "4258"
"Business &amp; Small Business" = "4259"
"Career &amp; Resume" = "4260"
"Computers &amp; Technology" = "4261"
"Dance" = "8181"
"Donor (for Development Use Only)" = "4628"
"Early Literacy" = "8182"
"Education/College Admissions/Test Prep" = "4262"
"Finance" = "4264"
"Food" = "4265"
"Genealogy" = "4266"
"Health, Fitness &amp; Wellness" = "4267"
"History/Social Studies" = "4268"
"Homework Help/Tutoring" = "4269"
"Information Literacy/Research Skills" = "4270"
"Language" = "4271"
"Library Promotion" = "4273"
"Literacy Instruction (CRW, ESOL)" = "4274"
"Literature, Poetry &amp; Writing" = "4275"
"Local Community" = "4272"
"Local History" = "7961"
"Maker Programs" = "7962"
"Maps &amp; Cartography" = "4684"
"Math &amp; Science" = "4276"
"Music" = "4277"
"Parenting" = "4278"
"Research Collection Orientation" = "8119"
"Research Collection-Based Assignment" = "8121"
"Research Collection-Based Class" = "8120"
"School Visit" = "6783"
"Society &amp; Culture" = "4279"
"Teen Advisory Group" = "7960"
"Theatre, Film &amp; Media" = "4280"
"Video Games" = "4281"
