"- None -" = "_none"
"Archival Materials" = "amat"
"Ask-A-Librarian" = "ask_a_librarian"
"homeworkNYC.org" = "homeworknyc"
"Job Information Center" = "job_information_center"
"Kanopy" = "kanopy"
"kids.nypl.org" = "kids"
"Local history collection" = "local_history"
"maps.nypl.org" = "maps"
"NYPL Catalog" = "catalog"
"NYPL Digital Gallery" = "digital_gallery"
"NYPL ebooks/downloadable audio books &amp; video" = "ebooks"
"NYPL Exhibition related materials" = "exhibitions"
"NYPL online exhibition site (list at http://www.nypl.org/events/online-exhibitions)" = "online_exhibitions"
"nypl.org" = "0"
"NYPL subscription database (i.e. Academic Search Premier, BrainPop…)" = "subscription_database"
"summerreading.org" = "summerreading"
