"- None -" = "_none"
"Curator" = "2746"
"Honoree" = "2751"
"Honoree" = "2752"
"Instructor" = "936"
"Interviewer" = "939"
"Library staff" = "8114"
"Moderator" = "938"
"Performer" = "940"
"Presenter" = "937"
"Speaker" = "2753"
