import requests

cookies = {
    "cookie": "value",
}

headers = {
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "accept-language": "en-US,en;q=0.9",
    "cache-control": "max-age=0",
    "content-type": "multipart/form-data; boundary=----WebKitFormBoundaryAHAw1gGIipKQtkkr",
    "origin": "https://www.nypl.org",
    "priority": "u=0, i",
    "referer": "https://www.nypl.org/node/add/event-program",
    "sec-ch-ua": '"Not(A:Brand";v="99", "Google Chrome";v="133", "Chromium";v="133"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"macOS"',
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "same-origin",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    # 'cookie': 'your_browser_cookies',
}

files = {
    "field_program_ignore_conflicts[und][1]": (None, "1"),
    "changed": (None, ""),
    "form_build_id": (None, "form-*******************************************"),
    "form_token": (None, "*******************************************"),
    "form_id": (None, "form_id_*****"),
    "title": (None, "*In-Person: Excel Genius Class 1: Logic Functions"),
    "body[und][0][summary]": (None, ""),
    "body[und][0][value]": (
        None,
        "<p><strong>This event will take place in person at the Seward Park Library in the Community Room.</strong></p>\n\n<p>&nbsp;</p>\n\n<p>This class covers how to use conditional logic in formulas and functions, allowing you to create formulas that act differently in different circumstances. Topics covered include: IF statements, nested IF statements, AND &amp; OR logic functions.</p>\n\n<p>This class is part of our Excel Genius class series. To learn more, visit:&nbsp;bit.ly/3KBj04g<br>\n\t&nbsp;</p>\n",
    ),
    "body[und][0][format]": (None, "4"),
    "field_group_program_dates[und][0][field_date_time][und][0][show_todate]": (
        None,
        "1",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value][month]": (
        None,
        "3",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value][day]": (
        None,
        "4",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value][year]": (
        None,
        "2025",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value][hour]": (
        None,
        "11",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value][minute]": (
        None,
        "00",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value][ampm]": (
        None,
        "am",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value2][month]": (
        None,
        "3",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value2][day]": (
        None,
        "4",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value2][year]": (
        None,
        "2025",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value2][hour]": (
        None,
        "12",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value2][minute]": (
        None,
        "30",
    ),
    "field_group_program_dates[und][0][field_date_time][und][0][value2][ampm]": (
        None,
        "pm",
    ),
    "field_group_program_dates[und][0][field_date_status][und]": (None, "_none"),
    "field_group_program_dates[und][0][field_date_details][und][0][value]": (None, ""),
    "field_group_program_dates[und][0][field_total_adults][und][0][value]": (None, ""),
    "field_group_program_dates[und][0][field_total_young_adults][und][0][value]": (
        None,
        "",
    ),
    "field_group_program_dates[und][0][field_total_children][und][0][value]": (
        None,
        "",
    ),
    "field_group_program_dates[und][0][_weight]": (None, "0"),
    "field_group_program_location[und][0][field_location][und]": (None, "171"),
    "field_group_program_location[und][0][field_external_location][und][0][value]": (
        None,
        "",
    ),
    "field_group_program_location[und][0][_weight]": (None, "0"),
    "nypl_events_repeat[FREQ]": (None, "WEEKLY"),
    "nypl_events_repeat[daily][byday_radios]": (None, "INTERVAL"),
    "nypl_events_repeat[daily][INTERVAL_child]": (None, "1"),
    "nypl_events_repeat[weekly][INTERVAL]": (None, "1"),
    "nypl_events_repeat[monthly][day_month]": (None, "BYMONTHDAY_BYMONTH"),
    "nypl_events_repeat[monthly][BYMONTHDAY_BYMONTH_child][BYMONTHDAY]": (None, "1"),
    "nypl_events_repeat[monthly][BYDAY_BYMONTH_child][BYDAY_COUNT]": (None, "+1"),
    "nypl_events_repeat[monthly][BYDAY_BYMONTH_child][BYDAY_DAY]": (None, "SU"),
    "nypl_events_repeat[yearly][INTERVAL]": (None, "1"),
    "nypl_events_repeat[yearly][day_month]": (None, "BYMONTHDAY_BYMONTH"),
    "nypl_events_repeat[yearly][BYMONTHDAY_BYMONTH_child][BYMONTHDAY]": (None, "1"),
    "nypl_events_repeat[yearly][BYDAY_BYMONTH_child][BYDAY_COUNT]": (None, "+1"),
    "nypl_events_repeat[yearly][BYDAY_BYMONTH_child][BYDAY_DAY]": (None, "SU"),
    "nypl_events_repeat[range_of_repeat]": (None, "COUNT"),
    "nypl_events_repeat[count_child]": (None, ""),
    "nypl_events_repeat[until_child][datetime][date]": (None, ""),
    "nypl_events_repeat[until_child][tz]": (None, ""),
    "nypl_events_repeat[until_child][all_day]": (None, "1"),
    "nypl_events_repeat[until_child][granularity]": (
        None,
        'a:3:{i:0;s:4:"year";i:1;s:5:"month";i:2;s:3:"day";}',
    ),
    "nypl_events_repeat[exceptions][EXDATE][0][datetime][date]": (None, ""),
    "nypl_events_repeat[exceptions][EXDATE][0][tz]": (None, ""),
    "nypl_events_repeat[exceptions][EXDATE][0][all_day]": (None, "1"),
    "nypl_events_repeat[exceptions][EXDATE][0][granularity]": (
        None,
        'a:3:{i:0;s:4:"year";i:1;s:5:"month";i:2;s:3:"day";}',
    ),
    "nypl_events_repeat[additions][RDATE][0][datetime][date]": (None, ""),
    "nypl_events_repeat[additions][RDATE][0][tz]": (None, ""),
    "nypl_events_repeat[additions][RDATE][0][all_day]": (None, "1"),
    "nypl_events_repeat[additions][RDATE][0][granularity]": (
        None,
        'a:3:{i:0;s:4:"year";i:1;s:5:"month";i:2;s:3:"day";}',
    ),
    "field_event_type[und]": (None, "4315"),
    "field_event_topic[und]": (None, "4261"),
    "field_target_audience[und]": (None, "Adult"),
    "field_event_audience[und][]": (None, "4332"),
    "field_series[und][]": (None, "200787"),
    "field_exhibitions[und][0][nid]": (None, ""),
    "field_exhibitions[und][0][_weight]": (None, "0"),
    "field_grant_funder[und][0][value]": (None, ""),
    "field_sponsor[und][0][value]": (None, ""),
    "field_tickets_required[und]": (None, "_none"),
    "field_cost[und][0][value]": (None, ""),
    "field_ticket_details[und][0][value]": (None, ""),
    "field_ticket_link[und][0][title]": (None, ""),
    "field_ticket_link[und][0][url]": (None, ""),
    "field_signup_method[und]": (None, "966"),
    "field_registration_details[und][0][value]": (None, ""),
    "field_max_class_size[und][0][value]": (None, "20"),
    "field_signup_open[und][0][value][date]": (None, ""),
    "field_signup_open[und][0][value][time]": (None, ""),
    "field_skill_prerequisites[und][0][value]": (None, ""),
    "field_class_format[und]": (None, "_none"),
    "files[field_program_image_und_0]": ("", "", "application/octet-stream"),
    "field_program_image[und][0][_weight]": (None, "0"),
    "field_program_image[und][0][fid]": (None, "0"),
    "field_program_image[und][0][display]": (None, "1"),
    "field_image_gallery_include[und][0][nid]": (None, ""),
    "files[field_program_transcript_und_0]": ("", "", "application/octet-stream"),
    "field_program_transcript[und][0][fid]": (None, "0"),
    "field_program_transcript[und][0][display]": (None, "1"),
    "files[field_flyer_und_0]": ("", "", "application/octet-stream"),
    "field_flyer[und][0][fid]": (None, "0"),
    "field_flyer[und][0][display]": (None, "1"),
    "field_related_pubs[und][0][nid]": (None, ""),
    "field_related_pubs[und][0][_weight]": (None, "0"),
    "field_teacher_first_name[und][0][value]": (None, ""),
    "field_teacher_last_name[und][0][value]": (None, ""),
    "field_teacher_email[und][0][email]": (None, ""),
    "field_doe_school[und]": (None, ""),
    "field_teacher_phone_number[und][0][value]": (None, ""),
    "field_school_type[und]": (None, "_none"),
    "field_grade_age[und]": (None, "_none"),
    "field_doe_outreach_activities[und]": (None, "_none"),
    "field_comments[und][0][value]": (None, ""),
    "field_event_capacity[und][0][value]": (None, ""),
    "field_materials_used[und][0][value]": (None, ""),
    "field_preparation_totat_time[und][0][value]": (None, ""),
    "field_event_total_time[und][0][value]": (None, ""),
    "field_access_services_note[und]": (None, "1"),
    "field_person[und][0][value]": (None, "Kang Chen"),
    "field_person_type[und]": (None, "936"),
    "field_featured_event_homepage[und]": (None, "1"),
    "field_featured_event_date[und][0][value][month]": (None, ""),
    "field_featured_event_date[und][0][value][day]": (None, ""),
    "field_featured_event_date[und][0][value][year]": (None, ""),
    "field_featured_event_date[und][0][value][hour]": (None, ""),
    "field_featured_event_date[und][0][value][minute]": (None, ""),
    "field_featured_event_date[und][0][value][ampm]": (None, ""),
    "field_featured_event_date[und][0][value2][month]": (None, ""),
    "field_featured_event_date[und][0][value2][day]": (None, ""),
    "field_featured_event_date[und][0][value2][year]": (None, ""),
    "field_featured_event_date[und][0][value2][hour]": (None, ""),
    "field_featured_event_date[und][0][value2][minute]": (None, ""),
    "field_featured_event_date[und][0][value2][ampm]": (None, ""),
    "field_workflow_disclaimer[und][0][value]": (None, ""),
    "menu[link_title]": (None, ""),
    "menu[description]": (None, ""),
    "menu[parent]": (None, "main-menu:0"),
    "menu[weight]": (None, "0"),
    "log": (None, ""),
    "path[alias]": (None, ""),
    "metatags[und][title][value]": (None, "[node:title] | [site:name]"),
    "metatags[und][title][default]": (None, "[node:title] | [site:name]"),
    "metatags[und][description][value]": (None, "[node:summary]"),
    "metatags[und][description][default]": (None, "[node:summary]"),
    "metatags[und][abstract][value]": (None, ""),
    "metatags[und][abstract][default]": (None, ""),
    "metatags[und][keywords][value]": (
        None,
        "NYPL, The New York Public Library, Manhattan, Bronx, Staten Island",
    ),
    "metatags[und][keywords][default]": (
        None,
        "NYPL, The New York Public Library, Manhattan, Bronx, Staten Island",
    ),
    "metatags[und][author][value]": (None, ""),
    "metatags[und][robots][max-snippet]": (None, ""),
    "metatags[und][robots][max-image-preview]": (None, ""),
    "metatags[und][robots][max-video-preview]": (None, ""),
    "metatags[und][robots][default]": (None, ""),
    "metatags[und][news_keywords][value]": (None, ""),
    "metatags[und][news_keywords][default]": (None, ""),
    "metatags[und][standout][value]": (None, ""),
    "metatags[und][standout][default]": (None, ""),
    "metatags[und][rating][value]": (None, ""),
    "metatags[und][rating][default]": (None, ""),
    "metatags[und][referrer][value]": (None, ""),
    "metatags[und][referrer][default]": (None, ""),
    "metatags[und][rights][value]": (
        None,
        "© [current-date:custom:Y] The New York Public Library ",
    ),
    "metatags[und][rights][default]": (
        None,
        "© [current-date:custom:Y] The New York Public Library ",
    ),
    "metatags[und][image_src][value]": (None, ""),
    "metatags[und][image_src][default]": (None, ""),
    "metatags[und][canonical][value]": (None, ""),
    "metatags[und][canonical][default]": (None, ""),
    "metatags[und][set_cookie][value]": (None, ""),
    "metatags[und][shortlink][value]": (None, ""),
    "metatags[und][shortlink][default]": (None, ""),
    "metatags[und][original-source][value]": (None, ""),
    "metatags[und][original-source][default]": (None, ""),
    "metatags[und][prev][value]": (None, ""),
    "metatags[und][prev][default]": (None, ""),
    "metatags[und][next][value]": (None, ""),
    "metatags[und][next][default]": (None, ""),
    "metatags[und][content-language][value]": (None, ""),
    "metatags[und][content-language][default]": (None, ""),
    "metatags[und][geo.position][value]": (None, ""),
    "metatags[und][geo.position][default]": (None, ""),
    "metatags[und][geo.placename][value]": (None, ""),
    "metatags[und][geo.placename][default]": (None, ""),
    "metatags[und][geo.region][value]": (None, ""),
    "metatags[und][geo.region][default]": (None, ""),
    "metatags[und][icbm][value]": (None, ""),
    "metatags[und][icbm][default]": (None, ""),
    "metatags[und][refresh][value]": (None, ""),
    "metatags[und][refresh][default]": (None, ""),
    "metatags[und][revisit-after][value]": (None, ""),
    "metatags[und][revisit-after][period]": (None, ""),
    "metatags[und][revisit-after][default]": (None, ""),
    "metatags[und][pragma][value]": (None, ""),
    "metatags[und][pragma][default]": (None, ""),
    "metatags[und][cache-control][value]": (None, ""),
    "metatags[und][cache-control][default]": (None, ""),
    "metatags[und][expires][value]": (None, ""),
    "metatags[und][expires][default]": (None, ""),
    "metatags[und][google][value]": (None, ""),
    "metatags[und][og:type][value]": (None, ""),
    "metatags[und][og:type][default]": (None, ""),
    "metatags[und][og:url][value]": (None, "[current-page:url:absolute]"),
    "metatags[und][og:url][default]": (None, "[current-page:url:absolute]"),
    "metatags[und][og:title][value]": (None, "[node:title]"),
    "metatags[und][og:title][default]": (None, "[node:title]"),
    "metatags[und][og:determiner][value]": (None, ""),
    "metatags[und][og:determiner][default]": (None, ""),
    "metatags[und][og:description][value]": (None, "[node:summary]"),
    "metatags[und][og:description][default]": (None, "[node:summary]"),
    "metatags[und][og:updated_time][value]": (None, ""),
    "metatags[und][og:updated_time][default]": (None, ""),
    "metatags[und][og:see_also][value]": (None, ""),
    "metatags[und][og:see_also][default]": (None, ""),
    "metatags[und][og:image][value]": (
        None,
        "https://ux-static.nypl.org/images/social-sharing/default+events+img-FINAL_868x455.png",
    ),
    "metatags[und][og:image][default]": (
        None,
        "https://ux-static.nypl.org/images/social-sharing/default+events+img-FINAL_868x455.png",
    ),
    "metatags[und][og:image:url][value]": (None, ""),
    "metatags[und][og:image:url][default]": (None, ""),
    "metatags[und][og:image:secure_url][value]": (None, ""),
    "metatags[und][og:image:secure_url][default]": (None, ""),
    "metatags[und][og:image:alt][value]": (None, ""),
    "metatags[und][og:image:type][value]": (None, "image/png"),
    "metatags[und][og:image:type][default]": (None, "image/png"),
    "metatags[und][og:image:width][value]": (None, "868"),
    "metatags[und][og:image:width][default]": (None, "868"),
    "metatags[und][og:image:height][value]": (None, "455"),
    "metatags[und][og:image:height][default]": (None, "455"),
    "metatags[und][og:latitude][value]": (None, ""),
    "metatags[und][og:latitude][default]": (None, ""),
    "metatags[und][og:longitude][value]": (None, ""),
    "metatags[und][og:longitude][default]": (None, ""),
    "metatags[und][og:street_address][value]": (None, ""),
    "metatags[und][og:street_address][default]": (None, ""),
    "metatags[und][og:locality][value]": (None, ""),
    "metatags[und][og:locality][default]": (None, ""),
    "metatags[und][og:region][value]": (None, ""),
    "metatags[und][og:region][default]": (None, ""),
    "metatags[und][og:postal_code][value]": (None, ""),
    "metatags[und][og:postal_code][default]": (None, ""),
    "metatags[und][og:country_name][value]": (None, ""),
    "metatags[und][og:country_name][default]": (None, ""),
    "metatags[und][og:email][value]": (None, ""),
    "metatags[und][og:email][default]": (None, ""),
    "metatags[und][og:phone_number][value]": (None, ""),
    "metatags[und][og:phone_number][default]": (None, ""),
    "metatags[und][og:fax_number][value]": (None, ""),
    "metatags[und][og:fax_number][default]": (None, ""),
    "metatags[und][og:locale][value]": (None, ""),
    "metatags[und][og:locale][default]": (None, ""),
    "metatags[und][og:locale:alternate][value]": (None, ""),
    "metatags[und][og:locale:alternate][default]": (None, ""),
    "metatags[und][article:author][value]": (None, ""),
    "metatags[und][article:author][default]": (None, ""),
    "metatags[und][article:publisher][value]": (None, ""),
    "metatags[und][article:publisher][default]": (None, ""),
    "metatags[und][article:section][value]": (None, ""),
    "metatags[und][article:section][default]": (None, ""),
    "metatags[und][article:tag][value]": (None, ""),
    "metatags[und][article:tag][default]": (None, ""),
    "metatags[und][article:published_time][value]": (None, ""),
    "metatags[und][article:published_time][default]": (None, ""),
    "metatags[und][article:modified_time][value]": (None, ""),
    "metatags[und][article:modified_time][default]": (None, ""),
    "metatags[und][article:expiration_time][value]": (None, ""),
    "metatags[und][article:expiration_time][default]": (None, ""),
    "metatags[und][profile:first_name][value]": (None, ""),
    "metatags[und][profile:first_name][default]": (None, ""),
    "metatags[und][profile:last_name][value]": (None, ""),
    "metatags[und][profile:last_name][default]": (None, ""),
    "metatags[und][profile:username][value]": (None, ""),
    "metatags[und][profile:username][default]": (None, ""),
    "metatags[und][profile:gender][value]": (None, ""),
    "metatags[und][profile:gender][default]": (None, ""),
    "metatags[und][og:audio][value]": (None, ""),
    "metatags[und][og:audio][default]": (None, ""),
    "metatags[und][og:audio:secure_url][value]": (None, ""),
    "metatags[und][og:audio:secure_url][default]": (None, ""),
    "metatags[und][og:audio:type][value]": (None, ""),
    "metatags[und][og:audio:type][default]": (None, ""),
    "metatags[und][book:author][value]": (None, ""),
    "metatags[und][book:author][default]": (None, ""),
    "metatags[und][book:isbn][value]": (None, ""),
    "metatags[und][book:isbn][default]": (None, ""),
    "metatags[und][book:release_date][value]": (None, ""),
    "metatags[und][book:release_date][default]": (None, ""),
    "metatags[und][book:tag][value]": (None, ""),
    "metatags[und][book:tag][default]": (None, ""),
    "metatags[und][og:video:url][value]": (None, ""),
    "metatags[und][og:video:url][default]": (None, ""),
    "metatags[und][og:video:secure_url][value]": (None, ""),
    "metatags[und][og:video:secure_url][default]": (None, ""),
    "metatags[und][og:video:width][value]": (None, ""),
    "metatags[und][og:video:width][default]": (None, ""),
    "metatags[und][og:video:height][value]": (None, ""),
    "metatags[und][og:video:height][default]": (None, ""),
    "metatags[und][og:video:type][value]": (None, ""),
    "metatags[und][og:video:type][default]": (None, ""),
    "metatags[und][video:actor][value]": (None, ""),
    "metatags[und][video:actor][default]": (None, ""),
    "metatags[und][video:actor:role][value]": (None, ""),
    "metatags[und][video:actor:role][default]": (None, ""),
    "metatags[und][video:director][value]": (None, ""),
    "metatags[und][video:director][default]": (None, ""),
    "metatags[und][video:writer][value]": (None, ""),
    "metatags[und][video:writer][default]": (None, ""),
    "metatags[und][video:duration][value]": (None, ""),
    "metatags[und][video:duration][default]": (None, ""),
    "metatags[und][video:release_date][value]": (None, ""),
    "metatags[und][video:release_date][default]": (None, ""),
    "metatags[und][video:tag][value]": (None, ""),
    "metatags[und][video:tag][default]": (None, ""),
    "metatags[und][video:series][value]": (None, ""),
    "metatags[und][video:series][default]": (None, ""),
    "metatags[und][fb:admins][value]": (None, ""),
    "metatags[und][fb:admins][default]": (None, ""),
    "metatags[und][fb:app_id][value]": (None, ""),
    "metatags[und][fb:app_id][default]": (None, ""),
    "metatags[und][fb:pages][value]": (None, ""),
    "metatags[und][fb:pages][default]": (None, ""),
    "metatags[und][twitter:card][value]": (None, "summary_large_image"),
    "metatags[und][twitter:card][default]": (None, "summary_large_image"),
    "metatags[und][twitter:creator][value]": (None, ""),
    "metatags[und][twitter:creator][default]": (None, ""),
    "metatags[und][twitter:creator:id][value]": (None, ""),
    "metatags[und][twitter:creator:id][default]": (None, ""),
    "metatags[und][twitter:url][value]": (None, ""),
    "metatags[und][twitter:url][default]": (None, ""),
    "metatags[und][twitter:title][value]": (None, ""),
    "metatags[und][twitter:title][default]": (None, ""),
    "metatags[und][twitter:description][value]": (None, ""),
    "metatags[und][twitter:description][default]": (None, ""),
    "metatags[und][twitter:dnt][value]": (None, ""),
    "metatags[und][twitter:image][value]": (
        None,
        "https://ux-static.nypl.org/images/social-sharing/default+events+img-FINAL_868x489.png",
    ),
    "metatags[und][twitter:image][default]": (
        None,
        "https://ux-static.nypl.org/images/social-sharing/default+events+img-FINAL_868x489.png",
    ),
    "metatags[und][twitter:image:width][value]": (None, ""),
    "metatags[und][twitter:image:width][default]": (None, ""),
    "metatags[und][twitter:image:height][value]": (None, ""),
    "metatags[und][twitter:image:height][default]": (None, ""),
    "metatags[und][twitter:image:alt][value]": (None, ""),
    "metatags[und][twitter:image:alt][default]": (None, ""),
    "metatags[und][twitter:image0][value]": (None, ""),
    "metatags[und][twitter:image0][default]": (None, ""),
    "metatags[und][twitter:image1][value]": (None, ""),
    "metatags[und][twitter:image1][default]": (None, ""),
    "metatags[und][twitter:image2][value]": (None, ""),
    "metatags[und][twitter:image2][default]": (None, ""),
    "metatags[und][twitter:image3][value]": (None, ""),
    "metatags[und][twitter:image3][default]": (None, ""),
    "metatags[und][twitter:player][value]": (None, ""),
    "metatags[und][twitter:player][default]": (None, ""),
    "metatags[und][twitter:player:width][value]": (None, ""),
    "metatags[und][twitter:player:width][default]": (None, ""),
    "metatags[und][twitter:player:height][value]": (None, ""),
    "metatags[und][twitter:player:height][default]": (None, ""),
    "metatags[und][twitter:player:stream][value]": (None, ""),
    "metatags[und][twitter:player:stream][default]": (None, ""),
    "metatags[und][twitter:player:stream:content_type][value]": (None, ""),
    "metatags[und][twitter:player:stream:content_type][default]": (None, ""),
    "metatags[und][twitter:app:country][value]": (None, ""),
    "metatags[und][twitter:app:country][default]": (None, ""),
    "metatags[und][twitter:app:name:iphone][value]": (None, ""),
    "metatags[und][twitter:app:name:iphone][default]": (None, ""),
    "metatags[und][twitter:app:id:iphone][value]": (None, ""),
    "metatags[und][twitter:app:id:iphone][default]": (None, ""),
    "metatags[und][twitter:app:url:iphone][value]": (None, ""),
    "metatags[und][twitter:app:url:iphone][default]": (None, ""),
    "metatags[und][twitter:app:name:ipad][value]": (None, ""),
    "metatags[und][twitter:app:name:ipad][default]": (None, ""),
    "metatags[und][twitter:app:id:ipad][value]": (None, ""),
    "metatags[und][twitter:app:id:ipad][default]": (None, ""),
    "metatags[und][twitter:app:url:ipad][value]": (None, ""),
    "metatags[und][twitter:app:url:ipad][default]": (None, ""),
    "metatags[und][twitter:app:name:googleplay][value]": (None, ""),
    "metatags[und][twitter:app:name:googleplay][default]": (None, ""),
    "metatags[und][twitter:app:id:googleplay][value]": (None, ""),
    "metatags[und][twitter:app:id:googleplay][default]": (None, ""),
    "metatags[und][twitter:app:url:googleplay][value]": (None, ""),
    "metatags[und][twitter:app:url:googleplay][default]": (None, ""),
    "metatags[und][twitter:label1][value]": (None, ""),
    "metatags[und][twitter:label1][default]": (None, ""),
    "metatags[und][twitter:data1][value]": (None, ""),
    "metatags[und][twitter:data1][default]": (None, ""),
    "metatags[und][twitter:label2][value]": (None, ""),
    "metatags[und][twitter:label2][default]": (None, ""),
    "metatags[und][twitter:data2][value]": (None, ""),
    "metatags[und][twitter:data2][default]": (None, ""),
    "comment": (None, "1"),
    "additional_settings__active_tab": (None, "edit-menu"),
    "op": (None, "Save"),
}

response = requests.post(
    "https://www.nypl.org/node/add/event-program",
    cookies=cookies,
    headers=headers,
    files=files,
)
