"None" = "_none"
"Book Discussions/Literary Readings" = "4313"
"Building/Exhibition Tour" = "4314"
"Classes/Workshops" = "4315"
"Community Based Organization Visit (not for public website)" = "4316"
"Correctional Services (not for public events)" = "4317"
"Donor Meeting (for Development use only)" = "4318"
"Donor Reception (for Development use only)" = "4319"
"Early Literacy Outreach (Not Class Visits)" = "8184"
"Early Literacy Program (Misc.)" = "8190"
"Educator Programs/Professional Development" = "4263"
"Family Literacy Workshop" = "8189"
"Film/Video Screenings" = "4320"
"Games &amp; Gaming" = "4321"
"General Outreach" = "8113"
"Lectures, Panels &amp; Conversations" = "4322"
"MyLibraryNYC Outreach" = "6782"
"Networking/Social Gathering" = "4323"
"OST" = "7866"
"Performances" = "4324"
"Programs for Persons Without Homes" = "7700"
"School Visit" = "4325"
"Special Events" = "4326"
"Special Needs Programs - Contained" = "7697"
"Special Needs Programs - Inclusive" = "7696"
"Story Times/Read Alouds" = "4327"
"Targeted Outreach" = "8193"
