"None" = "_none"
"125th Street" = "2"
"125th Street, Children's Reading Room" = "725"
"125th Street, Children's Room" = "417"
"125th Street, Community" = "726"
"53rd Street" = "8160"
"53rd Street, 53rd Street Classroom A" = "8164"
"53rd Street, 53rd Street Community Room" = "8163"
"53rd Street, 53rd Street Teen Zone" = "8166"
"53rd Street, 53rd Street Theater" = "8162"
"58th Street" = "3"
"58th Street, Community Meeting Room" = "418"
"58th Street, Computer Classroom" = "627"
"67th Street" = "4"
"67th Street, Community Room" = "420"
"67th Street, Computer Classroom" = "421"
"67th Street, Story Hour Room" = "678"
"96th Street" = "5"
"96th Street, Auditorium" = "638"
"96th Street, Conference Room" = "639"
"96th Street, Story Hour Room" = "640"
"Aguilar" = "6"
"Aguilar, Adult Learning Center" = "968"
"Allerton" = "7"
"Allerton, Auditorium" = "426"
"Allerton, Children's Room" = "425"
"Andrew Heiskell" = "8"
"Andrew Heiskell, Children's Room" = "431"
"Andrew Heiskell, Community Meeting Room" = "432"
"Andrew Heiskell, First Floor" = "428"
"Andrew Heiskell, Second Floor" = "429"
"Battery Park City" = "2787"
"Battery Park City, Community Room" = "2790"
"Baychester" = "9"
"Baychester, Community Meeting Room" = "434"
"Belmont" = "10"
"Belmont, Atrium" = "2705"
"Belmont, Children's Room" = "358"
"Belmont, Community Meeting Room" = "359"
"Belmont, First Floor" = "356"
"Belmont, Second Floor" = "674"
"Bloomingdale" = "11"
"Bloomingdale, Auditorium" = "362"
"Bloomingdale, Children's Room" = "360"
"Bronx Library Center" = "12"
"Bronx Library Center, Adult Books Collection" = "440"
"Bronx Library Center, Adult Learning Center" = "100"
"Bronx Library Center, Auditorium" = "704"
"Bronx Library Center, Career Services" = "159"
"Bronx Library Center, Children's Room" = "439"
"Bronx Library Center, Latino and Puerto Rican Cultural Collection" = "155"
"Bronx Library Center, New Books and Media" = "882"
"Bronx Library Center, Reference Collection" = "883"
"Bronx Library Center, Technology Training Center" = "92"
"Bronx Library Center, Teen Center" = "157"
"Castle Hill" = "13"
"Charleston" = "8219"
"Chatham Square" = "15"
"Chatham Square, Children's Room" = "256"
"Chatham Square, Chinese Heritage Collection" = "459"
"Chatham Square, Community Room" = "666"
"City Island" = "16"
"City Island, Backyard Reading Garden" = "464"
"City Island, Community Meeting Room" = "465"
"Clason's Point" = "17"
"Clason's Point, Children's Room" = "2784"
"Clason's Point, Community Meeting Room" = "466"
"Clason's Point, First Floor" = "329"
"Clason's Point, Young Adult Area" = "2785"
"Columbus" = "18"
"Columbus, Children's Room" = "469"
"Columbus, Children's Room, Story Room" = "630"
"Columbus, Community Room" = "629"
"Columbus, Computer Lab" = "7646"
"Countee Cullen" = "19"
"Countee Cullen, Auditorium" = "247"
"Countee Cullen, Basement" = "449"
"Countee Cullen, Computer Lab" = "7647"
"Countee Cullen, Conference Room A" = "294"
"Countee Cullen, Exhibition Space" = "293"
"Countee Cullen, Mezzanine" = "249"
"Countee Cullen, Second Floor" = "276"
"Countee Cullen, Story Hour Room" = "297"
"Countee Cullen, TechConnect Computer Lab" = "295"
"Countee Cullen, Third Floor" = "250"
"Dongan Hills" = "20"
"Eastchester" = "22"
"Edenwald" = "23"
"Epiphany" = "24"
"Fort Washington" = "25"
"Fort Washington, Children's Room" = "379"
"Fort Washington, Community Room" = "380"
"Francis Martin" = "26"
"Francis Martin, Children's Room" = "383"
"Francis Martin, Community Room" = "875"
"George Bruce" = "27"
"George Bruce, Auditorium" = "483"
"George Bruce, Children's Room" = "482"
"George Bruce, Computer room" = "658"
"Grand Central" = "871"
"Grand Central, Community Room" = "2772"
"Grand Central, Teen Central" = "998"
"Grand Concourse" = "28"
"Grand Concourse, Children's Room" = "485"
"Grand Concourse, First Floor" = "484"
"Grand Concourse, Lower Level" = "486"
"Great Kills" = "29"
"Great Kills, Community Room" = "657"
"Hamilton Fish Park" = "30"
"Hamilton Fish Park, Auditorium" = "349"
"Hamilton Fish Park, First Floor" = "348"
"Hamilton Grange" = "31"
"Hamilton Grange, Children's Room" = "716"
"Hamilton Grange, Community Room" = "714"
"Hamilton Grange, Job Information Center" = "2698"
"Harlem" = "32"
"Harlem, Adult Learning Center" = "969"
"Harlem, Auditorium" = "844"
"Harry Belafonte" = "1"
"Harry Belafonte, Alvin Ailey Community Room" = "2803"
"High Bridge" = "33"
"Hudson Park" = "34"
"Huguenot Park" = "35"
"Hunts Point" = "37"
"Hunts Point, Children's Room" = "387"
"Hunts Point, Community Room" = "874"
"Inwood" = "38"
"Inwood, Auditorium" = "370"
"Inwood, Children's Program Room" = "367"
"Inwood, Classrooms" = "369"
"Jefferson Market" = "39"
"Jefferson Market, First Floor" = "402"
"Jerome Park" = "40"
"Jerome Park, Community Room" = "873"
"Kingsbridge" = "41"
"Kingsbridge, First Floor" = "324"
"Kips Bay" = "42"
"Kips Bay, Children's" = "119"
"Kips Bay, Community" = "120"
"Library for the Performing Arts" = "55"
"Library for the Performing Arts, Arts Administration" = "1006"
"Library for the Performing Arts, Astor Gallery" = "200"
"Library for the Performing Arts, Billy Rose Theatre Division" = "224"
"Library for the Performing Arts, Bruno Walter Auditorium" = "196"
"Library for the Performing Arts, Circulating Collections: Drama, Film, Dance, Arts Administration" = "220"
"Library for the Performing Arts, Circulating Collections: Music" = "219"
"Library for the Performing Arts, Dance" = "1002"
"Library for the Performing Arts, Drama" = "1003"
"Library for the Performing Arts, Harvey Fierstein Theatre Lab" = "1025"
"Library for the Performing Arts, Jerome Robbins Dance Division" = "225"
"Library for the Performing Arts, LPA Cafe" = "7921"
"Library for the Performing Arts, Music" = "1000"
"Library for the Performing Arts, Music Division" = "226"
"Library for the Performing Arts, Oenslager Gallery" = "223"
"Library for the Performing Arts, Plaza Level Lobby" = "2700"
"Library for the Performing Arts, Recorded Sound and Moving Image" = "1004"
"Library for the Performing Arts, Reserve Film and Video Collection" = "1005"
"Library for the Performing Arts, Rodgers and Hammerstein Archives of Recorded Sound" = "227"
"Library for the Performing Arts, Sound and Video Recordings" = "222"
"Library for the Performing Arts, Special Collections Reading Room" = "1112"
"Library for the Performing Arts, Theatre on Film and Tape Archive" = "218"
"Library for the Performing Arts, Third Floor Screening Room" = "7585"
"Macomb's Bridge" = "43"
"Mariners Harbor" = "7892"
"Melrose" = "44"
"Morningside Heights" = "46"
"Morningside Heights, Community Room" = "624"
"Morningside Heights, Computer Classroom" = "622"
"Morningside Heights, Story Hour Room" = "625"
"Morris Park" = "632"
"Morrisania" = "48"
"Mosholu" = "49"
"Mosholu, Adult/Young Adult" = "320"
"Mosholu, Auditorium" = "319"
"Mosholu, Children's collection" = "322"
"Mott Haven" = "50"
"Mott Haven, Community room" = "619"
"Mott Haven, Literacy Project Center" = "626"
"Muhlenberg" = "51"
"Muhlenberg, Community Room" = "4796"
"Muhlenberg, Conference Room" = "4797"
"Mulberry Street" = "495"
"NYPL Bookmobile, Bronx" = "8212"
"NYPL Bookmobile, Manhattan" = "8213"
"NYPL Bookmobile, Staten Island" = "8214"
"New Amsterdam" = "53"
"New Amsterdam, Auditorium" = "705"
"New Amsterdam, Ground Floor" = "384"
"New Dorp" = "54"
"Ottendorfer" = "56"
"Parkchester" = "57"
"Parkchester, Children's Room" = "390"
"Parkchester, Computer Lab" = "7648"
"Parkchester, Meeting Room" = "881"
"Parkchester, Young Adult Area" = "2706"
"Pelham Bay" = "58"
"Pelham Parkway-Van Nest" = "80"
"Port Richmond" = "59"
"Port Richmond, Auditorium" = "393"
"Port Richmond, Main Floor" = "391"
"Richmondtown" = "60"
"Richmondtown, Community Room" = "975"
"Richmondtown, Second Floor" = "885"
"Richmondtown, Technology Training Center" = "1027"
"Riverdale" = "61"
"Riverside" = "62"
"Roosevelt Island" = "63"
"Roosevelt Island, Circulation / Information Desk" = "318"
"Schomburg Center" = "64"
"Schomburg Center, American Negro Theatre" = "2699"
"Schomburg Center, Art and Artifacts Division" = "204"
"Schomburg Center, Exhibition Hall" = "852"
"Schomburg Center, JBH Research and Reference Division" = "205"
"Schomburg Center, Langston Hughes Auditorium" = "231"
"Schomburg Center, Latimer/Edison Gallery" = "230"
"Schomburg Center, Manuscripts, Archives and Rare Books Division" = "206"
"Schomburg Center, Moving Image and Recorded Sound Division" = "207"
"Schomburg Center, Photographs and Prints Division" = "208"
"Schomburg Center, Scholar Center" = "835"
"Schomburg Center, Schomburg Shop" = "229"
"Schomburg Center, Window Gallery" = "853"
"Schwarzman Building" = "36"
"Schwarzman Building, Allen Room" = "184"
"Schwarzman Building, Astor Hall" = "850"
"Schwarzman Building, Berg Collection of English and American Literature" = "199"
"Schwarzman Building, Berger Forum" = "1035"
"Schwarzman Building, Brooke Russell Astor Reading Room" = "202"
"Schwarzman Building, Celeste Auditorium" = "845"
"Schwarzman Building, Celeste Bartos Forum" = "165"
"Schwarzman Building, Cullman Center for Scholars &amp; Writers" = "182"
"Schwarzman Building, Edna Barnes Salomon Room" = "1041"
"Schwarzman Building, General Research Division" = "394"
"Schwarzman Building, General Research Division, Catalog Room" = "197"
"Schwarzman Building, General Research Division, Periodicals Room" = "173"
"Schwarzman Building, General Research Division, Rose Main Reading Room" = "195"
"Schwarzman Building, Gottesman Hall" = "178"
"Schwarzman Building, Irma Milstein Study, Room 120" = "8228"
"Schwarzman Building, Jewish Division" = "177"
"Schwarzman Building, Jill Kupin Rose Gallery" = "1040"
"Schwarzman Building, Lenox &amp; Astor Room, Room 216" = "8196"
"Schwarzman Building, Library Shop" = "179"
"Schwarzman Building, Lionel Pincus and Princess Firyal Map Division" = "175"
"Schwarzman Building, McGraw Rotunda" = "851"
"Schwarzman Building, Microforms" = "172"
"Schwarzman Building, Milstein Division of U.S. History, Local History &amp; Genealogy" = "176"
"Schwarzman Building, Milstein Division of U.S. History, Local History &amp; Genealogy, Milstein Microform Room" = "180"
"Schwarzman Building, North Gallery" = "847"
"Schwarzman Building, Pforzheimer Collection of Shelley and His Circle" = "198"
"Schwarzman Building, Plaza" = "7603"
"Schwarzman Building, Preservation" = "711"
"Schwarzman Building, President's Office" = "2800"
"Schwarzman Building, Print Gallery" = "848"
"Schwarzman Building, Prints and Photographs Study Room" = "192"
"Schwarzman Building, Rayner Special Collections Wing" = "849"
"Schwarzman Building, Rayner Special Collections Wing and Print Gallery" = "8192"
"Schwarzman Building, Shoichi Noma Reading Room" = "7590"
"Schwarzman Building, South Court Classroom A" = "1030"
"Schwarzman Building, South Court Classroom B" = "1031"
"Schwarzman Building, South Court Classrooms" = "846"
"Schwarzman Building, Wachenheim Gallery" = "174"
"Schwarzman Building, Wachenheim Trustees Room" = "181"
"Schwarzman Building, Wallach Division, Art &amp; Architecture Collection" = "246"
"Schwarzman Building, Wallach Division, Photography Collection" = "447"
"Schwarzman Building, Wallach Division, Picture Collection" = "688"
"Schwarzman Building, Wallach Division, Spencer Collection" = "621"
"Schwarzman Building, Wertheim Study" = "183"
"Sedgwick" = "66"
"Sedgwick, Children's Room" = "615"
"Sedgwick, Circulation Desk" = "612"
"Sedgwick, Community Room" = "613"
"Sedgwick, Story Hour Area" = "610"
"Seward Park" = "67"
"Seward Park, Adult Collection, Reference, Periodicals" = "169"
"Seward Park, Adult Learning Center" = "170"
"Seward Park, Children's Room" = "168"
"Seward Park, Community Room" = "171"
"Seward Park, Young Adult Collection, Video media, New Books" = "167"
"Soundview" = "68"
"South Beach" = "69"
"Spuyten Duyvil" = "70"
"St. Agnes" = "71"
"St. Agnes, Community Program Room" = "2782"
"St. Agnes, First Floor/Children's Room" = "2777"
"St. Agnes, Second Floor" = "2780"
"St. Agnes, Story Hour Room" = "2778"
"St. Agnes, The Pasculano Foundation Adult Learning Center" = "2781"
"St. George Library Center" = "72"
"St. George Library Center, Adult Learning Center" = "2796"
"St. George Library Center, Auditorium" = "385"
"St. George Library Center, Second Floor" = "414"
"St. George Library Center, TechConnect Lab" = "1026"
"St. George Library Center, TechConnect Lab" = "7650"
"Stapleton" = "73"
"Stapleton, Community Room" = "411"
"Stavros Niarchos Foundation Library" = "45"
"Stavros Niarchos Foundation Library, Children's Center" = "166"
"Stavros Niarchos Foundation Library, Event Center" = "7612"
"Stavros Niarchos Foundation Library, Exam Proctoring by appointment" = "1114"
"Stavros Niarchos Foundation Library, Pasculano Learning Center" = "8172"
"Stavros Niarchos Foundation Library, Regularly scheduled classes in computer skills and related topics" = "1131"
"Stavros Niarchos Foundation Library, Teen Center" = "8179"
"Terence Cardinal Cooke-Cathedral" = "14"
"Thomas Yoseloff Business Center at SNFL" = "65"
"Throg's Neck" = "74"
"Todt Hill-Westerleigh" = "75"
"Todt Hill-Westerleigh, Children's Room" = "888"
"Tompkins Square" = "76"
"Tompkins Square, Adult Learning Center" = "2791"
"Tompkins Square, Basement" = "2743"
"Tompkins Square, First" = "2695"
"Tompkins Square, Second" = "2696"
"Tompkins Square, Third Floor" = "2744"
"Tottenville" = "77"
"Tremont" = "78"
"Tremont, Community" = "810"
"Tremont, Computer Lab" = "7649"
"Van Cortlandt" = "79"
"Wakefield" = "81"
"Wakefield, Adult Learning Center" = "137"
"Wakefield, CRW Office" = "143"
"Washington Heights" = "82"
"Webster" = "83"
"Webster, Auditorium" = "458"
"West Farms" = "84"
"West Farms, Community Room" = "5312"
"West Farms, Story Hour Room" = "510"
"West Farms, Young Adult Literacy Program" = "508"
"West New Brighton" = "85"
"West New Brighton, Community Room" = "976"
"West New Brighton, Main Floor" = "407"
"Westchester Square" = "86"
"Westchester Square, Children's Room" = "266"
"Woodlawn Heights" = "87"
"Woodstock" = "88"
"Yorkville" = "89"
"Yorkville, Children's Room" = "285"
"Yorkville, Meeting Room" = "286"
